<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>get purchases</name>
   <tag></tag>
   <elementGuidId>953469cc-ba8e-474c-a15a-3f431cfc071b</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent></httpBodyContent>
   <httpBodyType></httpBodyType>
   <katalonVersion>9.6.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>GET</restRequestMethod>
   <restUrl>${host}/purchases?startDate=${currentdate}&amp;endDate=${futuredate}&amp;q=t&amp;page=1</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.host</defaultValue>
      <description></description>
      <id>707af2a8-a6bf-46ab-b19f-59a82a7977eb</id>
      <masked>false</masked>
      <name>host</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.currentdate</defaultValue>
      <description></description>
      <id>079e6eb0-7a7b-43c6-96d4-ff4af3794423</id>
      <masked>false</masked>
      <name>currentdate</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.futuredate</defaultValue>
      <description></description>
      <id>75ba7c9e-c8d4-4aea-8bbc-8824901bffe3</id>
      <masked>false</masked>
      <name>futuredate</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
