<?xml version="1.0" encoding="UTF-8"?>
<WebServiceRequestEntity>
   <description></description>
   <name>purchase</name>
   <tag></tag>
   <elementGuidId>c2dc79f0-a177-4fa8-82b8-81664a6af122</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>false</useRalativeImagePath>
   <autoUpdateContent>true</autoUpdateContent>
   <connectionTimeout>-1</connectionTimeout>
   <followRedirects>false</followRedirects>
   <httpBody></httpBody>
   <httpBodyContent>{
  &quot;text&quot;: &quot;{\n    \&quot;officeId\&quot;: \&quot;${officeId}\&quot;,\n    \&quot;date\&quot;: \&quot;${currentdate}\&quot;,\n    \&quot;invoice\&quot;: \&quot;INV/02/12/2023/001\&quot;,\n    \&quot;amount\&quot;: 14000,\n    \&quot;discount\&quot;: 0,\n    \&quot;description\&quot;: \&quot;test saja\&quot;,\n    \&quot;items\&quot; : [\n        {\n            \&quot;productId\&quot;: \&quot;${productId-1}\&quot;,\n            \&quot;quantity\&quot;: 4,\n            \&quot;cost\&quot;: 3500\n        }\n    ]\n}&quot;,
  &quot;contentType&quot;: &quot;text/plain&quot;,
  &quot;charset&quot;: &quot;UTF-8&quot;
}</httpBodyContent>
   <httpBodyType>text</httpBodyType>
   <katalonVersion>9.6.0</katalonVersion>
   <maxResponseSize>-1</maxResponseSize>
   <migratedVersion>5.4.1</migratedVersion>
   <path></path>
   <restRequestMethod>POST</restRequestMethod>
   <restUrl>${host}/purchases</restUrl>
   <serviceType>RESTful</serviceType>
   <soapBody></soapBody>
   <soapHeader></soapHeader>
   <soapRequestMethod></soapRequestMethod>
   <soapServiceEndpoint></soapServiceEndpoint>
   <soapServiceFunction></soapServiceFunction>
   <socketTimeout>-1</socketTimeout>
   <useServiceInfoFromWsdl>true</useServiceInfoFromWsdl>
   <variables>
      <defaultValue>GlobalVariable.host</defaultValue>
      <description></description>
      <id>159a4432-7e43-4a06-988a-3a191ee2e573</id>
      <masked>false</masked>
      <name>host</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.officeId</defaultValue>
      <description></description>
      <id>d22744a9-ab86-405a-b19f-cc227a3678aa</id>
      <masked>false</masked>
      <name>officeId</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.currentdate</defaultValue>
      <description></description>
      <id>0b949266-7325-43e2-8b94-8943ae3b132b</id>
      <masked>false</masked>
      <name>currentdate</name>
   </variables>
   <variables>
      <defaultValue>GlobalVariable.productId-1</defaultValue>
      <description></description>
      <id>c47e97db-58f4-4b0d-a504-48bc89000945</id>
      <masked>false</masked>
      <name>productId-1</name>
   </variables>
   <wsdlAddress></wsdlAddress>
</WebServiceRequestEntity>
